<?php

declare(strict_types=1);

$_ENV['Clash_Config'] = [
    'mixed-port' => 7890,
    'allow-lan' => false,
    'bind-address' => '*',
    'mode' => 'Rule',
    'unified-delay' => true,
    'ipv6' => true,
    'log-level' => 'info',
    'external-controller' => '127.0.0.1:9090',
    'secret' => 'Burst_XJJ#Clash',
    'profile' => [
        'store-selected' => true,
        'store-fake-ip' => true,
    ],
    'geox-url' => [
        'geoip' => 'https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geoip.dat',
        'geosite' => 'https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geosite.dat',
        'mmdb' => 'https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/country.mmdb',
    ],
    'tun' => [
      'enable' => false,
      'stack' => 'mixed',
      'auto-route' => true,
      'auto-redir' => true,
      'auto-detect-interface' => true,
      'endpoint-independent-nat' => true,
      'dns-hijack' => [
        'any:53',
        'tcp://any:53',
      ]
    ],
    'dns' => [
        'enable' => true,
        'ipv6' => true,
        'prefer-h3' => false,
        'enhanced-mode' => 'fake-ip',
        'fake-ip-range' => '198.18.0.1/16',
        'fake-ip-filter' => [
            '+.lan',
            '+.local',
            'localhost.ptlogin2.qq.com',
            '+.msftconnecttest.com',
            '+.msftncsi.com',
            'time.*.com',
            'ntp.*.com',
            '+.pool.ntp.org',
            '+.ntp.org.cn',
            '+.time.edu.cn',
            'time1.cloud.tencent.com',
        ],
        'nameserver' => [
            'https://223.5.5.5/dns-query',
            'https://doh.pub/dns-query',
            'https://dns.alidns.com/dns-query',
        ],
        'fallback' => [
            'tls://8.8.4.4',
            'tls://1.1.1.1',
        ],
        'default-nameserver' => [
            '223.5.5.5',
            '120.53.53.1',
        ],
        'proxy-server-nameserver' => [
            'https://doh.pub/dns-query',
            '223.5.5.5',
        ],
        'fallback-filter' => [
            'geoip' => true,
            'geoip-code' => 'CN',
            'geosite' => [
                'gfw',
            ],
            'ipcidr' => [
                '240.0.0.0/4',
            ],
        ],
    ],
    'sniffer' => [
            'enable' => true,
            'parse-pure-ip' => true,
            'sniff' => [
                'HTTP' => [
                    'ports' => [80],
                    'override-destination' => true,
                ],
                'TLS' => [
                    'ports' => [443, 8443],
                ],
                'QUIC' => [
                   'ports' => [443, 8443],
                ],
            ],
            'skip-domain' => [
               'Mijia Cloud',
        ],
    ],
];

$_ENV['Clash_Group_Indexes'] = [];
$_ENV['Clash_Group_Config'] = [
    'proxy-groups' => [
        [
            'name' => 'Default Proxy',
            'type' => 'select',
            'proxies' => [
                'Global',
                'DIRECT',
                'REJECT',
            ],
        ],
        [
            'name' => 'Global',
            'type' => 'select',
            'proxies' => [
                'HK',
                'US',
                'JP',
                'TW',
            ],
        ],
        [
            'name' => 'JP',
            'type' => 'select',
            'include-all' => true,
            'filter' => 'JP',
        ],
        [
            'name' => 'HK',
            'type' => 'select',
            'include-all' => true,
            'filter' => 'HK',
        ],
        [
            'name' => 'US',
            'type' => 'select',
            'include-all' => true,
            'filter' => 'US',
        ],
        [
            'name' => 'TW',
            'type' => 'select',
            'include-all' => true,
            'filter' => 'TW',
        ],
        [
            'name' => 'AI Services',
            'type' => 'select',
            'proxies' => [
                'JP',
                'US',
            ],
        ],
        [
            'name' => 'Microsoft & Apple',
            'type' => 'select',
            'proxies' => [
                'Default Proxy',
                'HK',
                'JP',
                'US',
                'TW',
                'DIRECT',
            ],
        ],
        [
            'name' => 'Stream',
            'type' => 'select',
            'proxies' => [
                'Default Proxy',
                'HK',
                'JP',
                'US',
                'TW',
            ],
        ],
        [
            'name' => 'Steam Download',
            'type' => 'select',
            'proxies' => [
                'Default Proxy',
                'HK',
                'JP',
                'US',
                'TW',
                'DIRECT',
            ],
        ],
        [
            'name' => 'Final Match',
            'type' => 'select',
            'proxies' => [
                'Default Proxy',
                'HK',
                'JP',
                'US',
                'TW',
                'DIRECT',
            ],
        ],
    ],
    'rule-providers' => [
        'ad-reject' => [
            'type' => 'http',
            'behavior' => 'domain',
            'format' => 'yaml',
            'url' => 'https://fastly.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/reject.txt',
            'path' => './ruleset/loyalsoldier/reject.yaml',
            'interval' => 86400,
        ],
    ],
    'rules' => [
        'DOMAIN-SUFFIX,local,DIRECT',
        'DOMAIN-SUFFIX,arpa,DIRECT',
        'GEOIP,private,DIRECT,no-resolve',
        'RULE-SET,ad-reject,REJECT',
        'DOMAIN,ai-gateway.vercel.sh,AI Services',
        'DOMAIN,api.github.com,AI Services',
        'DOMAIN,apple-relay.apple.com,AI Services',
        'DOMAIN,apple-relay.cloudflare.com,AI Services',
        'DOMAIN,apple-relay.fastly-edge.com,AI Services',
        'DOMAIN,cp4.cloudflare.com,AI Services',
        'DOMAIN,gateway.ai.cloudflare.com,AI Services',
        'DOMAIN,gateway.icloud.com,AI Services',
        'DOMAIN,gspe1-ssl.ls.apple.com,AI Services',
        'DOMAIN,guzzoni.apple.com,AI Services',
        'DOMAIN-KEYWORD,openai,AI Services',
        'DOMAIN-SUFFIX,ai.com,AI Services',
        'DOMAIN-SUFFIX,anthropic.com,AI Services',
        'DOMAIN-SUFFIX,cerebras.ai,AI Services',
        'DOMAIN-SUFFIX,chat.com,AI Services',
        'DOMAIN-SUFFIX,chatgpt.com,AI Services',
        'DOMAIN-SUFFIX,claude.ai,AI Services',
        'DOMAIN-SUFFIX,claude.com,AI Services',
        'DOMAIN-SUFFIX,clipdrop.co,AI Services',
        'DOMAIN-SUFFIX,dify.ai,AI Services',
        'DOMAIN-SUFFIX,grok.com,AI Services',
        'DOMAIN-SUFFIX,groq.com,AI Services',
        'DOMAIN-SUFFIX,jasper.ai,AI Services',
        'DOMAIN-SUFFIX,meta.ai,AI Services',
        'DOMAIN-SUFFIX,oaistatic.com,AI Services',
        'DOMAIN-SUFFIX,oaiusercontent.com,AI Services',
        'DOMAIN-SUFFIX,openart.ai,AI Services',
        'DOMAIN-SUFFIX,perplexity.ai,AI Services',
        'DOMAIN-SUFFIX,poe.com,AI Services',
        'DOMAIN-SUFFIX,smoot.apple.com,AI Services',
        'DOMAIN-SUFFIX,sora.com,AI Services',
        'DOMAIN-SUFFIX,x.ai,AI Services',
        'DOMAIN-SUFFIX,wifiman.com,Default Proxy',
        'GEOSITE,google,Default Proxy',
        'GEOSITE,apple,Microsoft & Apple',
        'GEOSITE,microsoft,Microsoft & Apple',
        'GEOSITE,category-entertainment,Stream',
        'GEOSITE,category-game-platforms-download,Steam Download',
        'GEOSITE,cn,DIRECT',
        'GEOIP,CN,DIRECT',
        'MATCH,Final Match',
    ],
];

$_ENV['Stash_Config'] = [
    'mode' => 'rule',
    'log-level' => 'info',
    'dns' => [
        'default-nameserver' => [
            '223.5.5.5',
            '114.114.114.114',
            'system',
        ],
        'nameserver' => [
            'https://doh.pub/dns-query',
            'https://dns.alidns.com/dns-query',
        ],
        'follow-rule' => false,
    ],
];

$_ENV['Stash_Group_Indexes'] = [];
$_ENV['Stash_Group_Config'] = [
    'proxy-groups' => [
        [
            'name' => 'Default Proxy',
            'type' => 'select',
            'proxies' => [
                'Global',
                'DIRECT',
                'REJECT',
            ],
        ],
        [
            'name' => 'Global',
            'type' => 'select',
            'proxies' => [
                'HK',
                'US',
                'JP',
                'TW',
            ],
        ],
        [
            'name' => 'JP',
            'type' => 'select',
            'include-all' => true,
            'filter' => 'JP',
        ],
        [
            'name' => 'HK',
            'type' => 'select',
            'include-all' => true,
            'filter' => 'HK',
        ],
        [
            'name' => 'US',
            'type' => 'select',
            'include-all' => true,
            'filter' => 'US',
        ],
        [
            'name' => 'TW',
            'type' => 'select',
            'include-all' => true,
            'filter' => 'TW',
        ],
        [
            'name' => 'AI Services',
            'type' => 'select',
            'proxies' => [
                'JP',
                'US',
            ],
        ],
        [
            'name' => 'Microsoft & Apple',
            'type' => 'select',
            'proxies' => [
                'Default Proxy',
                'HK',
                'JP',
                'US',
                'TW',
            ],
        ],
        [
            'name' => 'Stream',
            'type' => 'select',
            'proxies' => [
                'Default Proxy',
                'HK',
                'JP',
                'US',
                'TW',
            ],
        ],
        [
            'name' => 'Final Match',
            'type' => 'select',
            'proxies' => [
                'Default Proxy',
                'HK',
                'JP',
                'US',
                'TW',
                'DIRECT',
            ],
        ],
    ],
    'rule-providers' => [
        'ad-reject' => [
            'type' => 'http',
            'behavior' => 'domain',
            'format' => 'yaml',
            'url' => 'https://fastly.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/reject.txt',
            'interval' => 86400,
        ],
        'lan-cidr' => [
            'type' => 'http',
            'behavior' => 'ipcidr',
            'format' => 'yaml',
            'url' => 'https://fastly.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/lancidr.txt',
            'interval' => 86400,
        ],
    ],
    'rules' => [
        'DOMAIN-SUFFIX,local,DIRECT',
        'DOMAIN-SUFFIX,arpa,DIRECT',
        'RULE-SET,lan-cidr,DIRECT,no-resolve',
        'RULE-SET,ad-reject,REJECT',
        'DOMAIN,ai-gateway.vercel.sh,AI Services',
        'DOMAIN,api.github.com,AI Services',
        'DOMAIN,apple-relay.apple.com,AI Services',
        'DOMAIN,apple-relay.cloudflare.com,AI Services',
        'DOMAIN,apple-relay.fastly-edge.com,AI Services',
        'DOMAIN,cp4.cloudflare.com,AI Services',
        'DOMAIN,gateway.ai.cloudflare.com,AI Services',
        'DOMAIN,gateway.icloud.com,AI Services',
        'DOMAIN,gspe1-ssl.ls.apple.com,AI Services',
        'DOMAIN,guzzoni.apple.com,AI Services',
        'DOMAIN-KEYWORD,openai,AI Services',
        'DOMAIN-SUFFIX,ai.com,AI Services',
        'DOMAIN-SUFFIX,anthropic.com,AI Services',
        'DOMAIN-SUFFIX,cerebras.ai,AI Services',
        'DOMAIN-SUFFIX,chat.com,AI Services',
        'DOMAIN-SUFFIX,chatgpt.com,AI Services',
        'DOMAIN-SUFFIX,claude.ai,AI Services',
        'DOMAIN-SUFFIX,claude.com,AI Services',
        'DOMAIN-SUFFIX,clipdrop.co,AI Services',
        'DOMAIN-SUFFIX,dify.ai,AI Services',
        'DOMAIN-SUFFIX,grok.com,AI Services',
        'DOMAIN-SUFFIX,groq.com,AI Services',
        'DOMAIN-SUFFIX,jasper.ai,AI Services',
        'DOMAIN-SUFFIX,meta.ai,AI Services',
        'DOMAIN-SUFFIX,oaistatic.com,AI Services',
        'DOMAIN-SUFFIX,oaiusercontent.com,AI Services',
        'DOMAIN-SUFFIX,openart.ai,AI Services',
        'DOMAIN-SUFFIX,perplexity.ai,AI Services',
        'DOMAIN-SUFFIX,poe.com,AI Services',
        'DOMAIN-SUFFIX,smoot.apple.com,AI Services',
        'DOMAIN-SUFFIX,sora.com,AI Services',
        'DOMAIN-SUFFIX,x.ai,AI Services',
        'DOMAIN-SUFFIX,wifiman.com,Default Proxy',
        'GEOSITE,google,Default Proxy',
        'GEOSITE,apple,Microsoft & Apple',
        'GEOSITE,microsoft,Microsoft & Apple',
        'GEOSITE,category-entertainment,Stream',
        'GEOSITE,cn,DIRECT',
        'GEOIP,CN,DIRECT',
        'MATCH,Final Match',
    ],
];
