<?php

declare(strict_types=1);

// Independent Clash Meta for Android profile.
return [
    'mixed-port' => 7890,
    'allow-lan' => false,
    'bind-address' => '*',
    'mode' => 'rule',
    'unified-delay' => true,
    'tcp-concurrent' => true,
    'ipv6' => true,
    'log-level' => 'warning',
    'profile' => [
        'store-selected' => true,
        'store-fake-ip' => true,
    ],
    'geox-url' => [
        'geoip' => 'https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geoip.dat',
        'geosite' => 'https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geosite.dat',
        'mmdb' => 'https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/country.mmdb',
    ],
    'tun' => [
      'enable' => false,
      'stack' => 'mixed',
      'auto-route' => true,
      'auto-detect-interface' => true,
      'endpoint-independent-nat' => false,
      'dns-hijack' => [
        'any:53',
        'tcp://any:53',
      ]
    ],
    'dns' => [
        'enable' => true,
        'ipv6' => true,
        'prefer-h3' => false,
        'respect-rules' => true,
        'enhanced-mode' => 'fake-ip',
        'fake-ip-range' => '198.18.0.1/16',
        'fake-ip-filter' => [
            '+.lan',
            '+.local',
            'localhost.ptlogin2.qq.com',
            '+.msftconnecttest.com',
            '+.msftncsi.com',
            'time.*.com',
            'ntp.*.com',
            '+.pool.ntp.org',
            '+.ntp.org.cn',
            '+.time.edu.cn',
            'time1.cloud.tencent.com',
        ],
        // Keep remote DNS independent of Default Proxy's DIRECT/REJECT choices.
        'nameserver' => [
            'tls://8.8.4.4#Global',
            'tls://1.1.1.1#Global',
        ],
        'default-nameserver' => [
            '223.5.5.5',
            '120.53.53.1',
        ],
        'proxy-server-nameserver' => [
            'https://doh.pub/dns-query',
            '223.5.5.5',
        ],
        'direct-nameserver' => [
            'https://223.5.5.5/dns-query#DIRECT',
            'https://doh.pub/dns-query#DIRECT',
        ],
        'direct-nameserver-follow-policy' => true,
        'nameserver-policy' => [
            'geosite:cn' => [
                'https://223.5.5.5/dns-query#DIRECT',
                'https://doh.pub/dns-query#DIRECT',
            ],
            '+.lan' => 'system',
            '+.local' => 'system',
        ],
    ],
    'sniffer' => [
            'enable' => true,
            'parse-pure-ip' => true,
            'override-destination' => false,
            'sniff' => [
                'HTTP' => [
                    'ports' => [80],
                    'override-destination' => true,
                ],
                'TLS' => [
                    'ports' => [443, 8443],
                ],
                'QUIC' => [
                   'ports' => [443, 8443],
                ],
            ],
            'skip-domain' => [
               'Mijia Cloud',
            ],
    ],
    'proxy-groups' => [
        [
            'name' => 'Default Proxy',
            'type' => 'select',
            'proxies' => [
                'Global',
                'DIRECT',
                'REJECT',
            ],
        ],
        [
            'name' => 'Global',
            'type' => 'select',
            'include-all-proxies' => true,
            'proxies' => [
                'HK',
                'US',
                'JP',
                'TW',
            ],
        ],
        [
            'name' => 'JP',
            'type' => 'select',
            'include-all' => true,
            'filter' => 'JP',
            'empty-fallback' => 'REJECT',
        ],
        [
            'name' => 'HK',
            'type' => 'select',
            'include-all' => true,
            'filter' => 'HK',
            'empty-fallback' => 'REJECT',
        ],
        [
            'name' => 'US',
            'type' => 'select',
            'include-all' => true,
            'filter' => 'US',
            'empty-fallback' => 'REJECT',
        ],
        [
            'name' => 'TW',
            'type' => 'select',
            'include-all' => true,
            'filter' => 'TW',
            'empty-fallback' => 'REJECT',
        ],
        [
            'name' => 'AI Services',
            'type' => 'select',
            'proxies' => [
                'JP',
                'US',
            ],
        ],
        [
            'name' => 'Microsoft & Apple',
            'type' => 'select',
            'proxies' => [
                'Default Proxy',
                'HK',
                'JP',
                'US',
                'TW',
                'DIRECT',
            ],
        ],
        [
            'name' => 'Stream',
            'type' => 'select',
            'proxies' => [
                'Default Proxy',
                'HK',
                'JP',
                'US',
                'TW',
            ],
        ],
        [
            'name' => 'Steam Download',
            'type' => 'select',
            'proxies' => [
                'DIRECT',
                'Default Proxy',
                'HK',
                'JP',
                'US',
                'TW',
            ],
        ],
        [
            'name' => 'Securities',
            'type' => 'select',
            'proxies' => [
                'Default Proxy',
                'HK',
                'US',
                'JP',
                'TW',
                'DIRECT',
            ],
        ],
        [
            'name' => 'Final Match',
            'type' => 'select',
            'proxies' => [
                'Default Proxy',
                'HK',
                'JP',
                'US',
                'TW',
                'DIRECT',
            ],
        ],
    ],
    'rule-providers' => [
        'ad-reject' => [
            'type' => 'http',
            'behavior' => 'domain',
            'format' => 'yaml',
            'url' => 'https://fastly.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/reject.txt',
            'path' => './ruleset/loyalsoldier/reject.yaml',
            'interval' => 86400,
        ],
    ],
    'rules' => [
        'DOMAIN-SUFFIX,lan,DIRECT',
        'DOMAIN-SUFFIX,local,DIRECT',
        'DOMAIN-SUFFIX,arpa,DIRECT',
        'GEOIP,private,DIRECT,no-resolve',
        'RULE-SET,ad-reject,REJECT',
        'DOMAIN,ai-gateway.vercel.sh,AI Services',
        'DOMAIN,api.github.com,AI Services',
        'DOMAIN,apple-relay.apple.com,AI Services',
        'DOMAIN,apple-relay.cloudflare.com,AI Services',
        'DOMAIN,apple-relay.fastly-edge.com,AI Services',
        'DOMAIN,cp4.cloudflare.com,AI Services',
        'DOMAIN,gateway.ai.cloudflare.com,AI Services',
        'DOMAIN,gateway.icloud.com,AI Services',
        'DOMAIN,gspe1-ssl.ls.apple.com,AI Services',
        'DOMAIN,guzzoni.apple.com,AI Services',
        'DOMAIN-KEYWORD,openai,AI Services',
        'DOMAIN-SUFFIX,ai.com,AI Services',
        'DOMAIN-SUFFIX,anthropic.com,AI Services',
        'DOMAIN-SUFFIX,cerebras.ai,AI Services',
        'DOMAIN-SUFFIX,chat.com,AI Services',
        'DOMAIN-SUFFIX,chatgpt.com,AI Services',
        'DOMAIN-SUFFIX,claude.ai,AI Services',
        'DOMAIN-SUFFIX,claude.com,AI Services',
        'DOMAIN-SUFFIX,clipdrop.co,AI Services',
        'DOMAIN-SUFFIX,dify.ai,AI Services',
        'DOMAIN-SUFFIX,grok.com,AI Services',
        'DOMAIN-SUFFIX,groq.com,AI Services',
        'DOMAIN-SUFFIX,jasper.ai,AI Services',
        'DOMAIN-SUFFIX,meta.ai,AI Services',
        'DOMAIN-SUFFIX,oaistatic.com,AI Services',
        'DOMAIN-SUFFIX,oaiusercontent.com,AI Services',
        'DOMAIN-SUFFIX,openart.ai,AI Services',
        'DOMAIN-SUFFIX,perplexity.ai,AI Services',
        'DOMAIN-SUFFIX,poe.com,AI Services',
        'DOMAIN-SUFFIX,smoot.apple.com,AI Services',
        'DOMAIN-SUFFIX,sora.com,AI Services',
        'DOMAIN-SUFFIX,x.ai,AI Services',
        'DOMAIN-SUFFIX,wifiman.com,Default Proxy',
        'GEOSITE,google,Default Proxy',
        // GitHub is included in microsoft; match it first to keep its exit independent.
        'GEOSITE,github,Default Proxy',
        'GEOSITE,apple,Microsoft & Apple',
        'GEOSITE,microsoft,Microsoft & Apple',
        // mihomo supports geosite attribute filtering (name@attr) even though
        // its wiki does not document it; Stash may not, so its block inlines
        // the equivalent domains. steam@cn must precede category-entertainment,
        // which swallows the untagged steam domains via category-games-!cn.
        'GEOSITE,steam@cn,Steam Download',
        'GEOSITE,category-game-platforms-download@cn,DIRECT',
        'DOMAIN-SUFFIX,steamcontent.com,Steam Download',
        'DOMAIN-SUFFIX,steamserver.net,Steam Download',
        'DOMAIN,steampipe.akamaized.net,Steam Download',
        'DOMAIN,steam.apac.qtlglb.com,Steam Download',
        'GEOSITE,category-game-platforms-download,Steam Download',
        'GEOSITE,category-entertainment,Stream',
        'GEOSITE,futu,Securities',
        'GEOSITE,itiger,Securities',
        'GEOSITE,ibkr,Securities',
        'GEOSITE,cn,DIRECT',
        'GEOIP,CN,DIRECT',
        'MATCH,Final Match',
    ],
];
