<?php

declare(strict_types=1);

// Dedicated profile for clash.md / Hako. Contains no user credentials.
// MRS sources: https://github.com/MetaCubeX/meta-rules-dat
// Ads use the smaller category-ads-all set, not Loyalsoldier's complete reject list.
// DNS uses domestic resolvers for China domains; other queries go through Default Proxy.
// Keep mixed explicitly: omitting the stack selects gVisor in the Apple client.
return [
    'mode' => 'rule',
    'unified-delay' => true,
    'tcp-concurrent' => true,
    'ipv6' => true,
    'log-level' => 'warning',
    'profile' => [
        'store-selected' => true,
        'store-fake-ip' => true,
    ],
    'dns' => [
        'enable' => true,
        'ipv6' => true,
        'prefer-h3' => false,
        'respect-rules' => true,
        'enhanced-mode' => 'fake-ip',
        'fake-ip-range' => '198.18.0.1/16',
        'fake-ip-filter' => [
            '+.lan',
            '+.local',
            'localhost.ptlogin2.qq.com',
            '+.msftconnecttest.com',
            '+.msftncsi.com',
            'time.*.com',
            'ntp.*.com',
            '+.pool.ntp.org',
            '+.ntp.org.cn',
            '+.time.edu.cn',
            'time1.cloud.tencent.com',
        ],
        'nameserver' => [
            'tls://8.8.4.4#Default Proxy',
            'tls://1.1.1.1#Default Proxy',
        ],
        'default-nameserver' => [
            '223.5.5.5',
            '120.53.53.1',
        ],
        'proxy-server-nameserver' => [
            'https://doh.pub/dns-query',
            '223.5.5.5',
        ],
        'nameserver-policy' => [
            'rule-set:site-cn' => [
                'https://223.5.5.5/dns-query',
                'https://doh.pub/dns-query',
            ],
            '+.lan' => 'system',
            '+.local' => 'system',
        ],
        'cache-algorithm' => 'lru',
        'cache-max-size' => 1024,
    ],
    'sniffer' => [
        'enable' => false,
    ],
    'proxy-groups' => [
        [
            'name' => 'Default Proxy',
            'type' => 'select',
            'proxies' => [
                'Global',
                'DIRECT',
                'REJECT',
            ],
        ],
        [
            'name' => 'Global',
            'type' => 'select',
            'proxies' => [
                'HK',
                'US',
                'JP',
                'TW',
            ],
        ],
        [
            'name' => 'JP',
            'type' => 'select',
            'filter' => 'JP',
        ],
        [
            'name' => 'HK',
            'type' => 'select',
            'filter' => 'HK',
        ],
        [
            'name' => 'US',
            'type' => 'select',
            'filter' => 'US',
        ],
        [
            'name' => 'TW',
            'type' => 'select',
            'filter' => 'TW',
        ],
        [
            'name' => 'AI Services',
            'type' => 'select',
            'proxies' => [
                'JP',
                'US',
            ],
        ],
        [
            'name' => 'Microsoft & Apple',
            'type' => 'select',
            'proxies' => [
                'Default Proxy',
                'HK',
                'JP',
                'US',
                'TW',
                'DIRECT',
            ],
        ],
        [
            'name' => 'Stream',
            'type' => 'select',
            'proxies' => [
                'Default Proxy',
                'HK',
                'JP',
                'US',
                'TW',
            ],
        ],
        [
            'name' => 'Steam Download',
            'type' => 'select',
            'proxies' => [
                'DIRECT',
                'Default Proxy',
                'HK',
                'JP',
                'US',
                'TW',
            ],
        ],
        [
            'name' => 'Securities',
            'type' => 'select',
            'proxies' => [
                'Default Proxy',
                'HK',
                'US',
                'JP',
                'TW',
                'DIRECT',
            ],
        ],
        [
            'name' => 'Final Match',
            'type' => 'select',
            'proxies' => [
                'Default Proxy',
                'HK',
                'JP',
                'US',
                'TW',
                'DIRECT',
            ],
        ],
    ],
    'rule-providers' => [
        'ad-reject' => [
            'type' => 'http',
            'behavior' => 'domain',
            'format' => 'mrs',
            'url' => 'https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/'
                . 'geo/geosite/category-ads-all.mrs',
            'path' => './ruleset/ad-reject.mrs',
            'interval' => 86400,
        ],
        'ip-private' => [
            'type' => 'http',
            'behavior' => 'ipcidr',
            'format' => 'mrs',
            'url' => 'https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geoip/private.mrs',
            'path' => './ruleset/ip-private.mrs',
            'interval' => 86400,
        ],
        'site-google' => [
            'type' => 'http',
            'behavior' => 'domain',
            'format' => 'mrs',
            'url' => 'https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/google.mrs',
            'path' => './ruleset/site-google.mrs',
            'interval' => 86400,
        ],
        'site-apple' => [
            'type' => 'http',
            'behavior' => 'domain',
            'format' => 'mrs',
            'url' => 'https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/apple.mrs',
            'path' => './ruleset/site-apple.mrs',
            'interval' => 86400,
        ],
        'site-microsoft' => [
            'type' => 'http',
            'behavior' => 'domain',
            'format' => 'mrs',
            'url' => 'https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/microsoft.mrs',
            'path' => './ruleset/site-microsoft.mrs',
            'interval' => 86400,
        ],
        'site-steam-cn' => [
            'type' => 'http',
            'behavior' => 'domain',
            'format' => 'mrs',
            'url' => 'https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/steam@cn.mrs',
            'path' => './ruleset/site-steam-cn.mrs',
            'interval' => 86400,
        ],
        'site-category-game-platforms-download-cn' => [
            'type' => 'http',
            'behavior' => 'domain',
            'format' => 'mrs',
            'url' => 'https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/'
                . 'geo/geosite/category-game-platforms-download@cn.mrs',
            'path' => './ruleset/site-category-game-platforms-download-cn.mrs',
            'interval' => 86400,
        ],
        'site-category-game-platforms-download' => [
            'type' => 'http',
            'behavior' => 'domain',
            'format' => 'mrs',
            'url' => 'https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/'
                . 'geo/geosite/category-game-platforms-download.mrs',
            'path' => './ruleset/site-category-game-platforms-download.mrs',
            'interval' => 86400,
        ],
        'site-category-entertainment' => [
            'type' => 'http',
            'behavior' => 'domain',
            'format' => 'mrs',
            'url' => 'https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/'
                . 'geo/geosite/category-entertainment.mrs',
            'path' => './ruleset/site-category-entertainment.mrs',
            'interval' => 86400,
        ],
        'site-futu' => [
            'type' => 'http',
            'behavior' => 'domain',
            'format' => 'mrs',
            'url' => 'https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/futu.mrs',
            'path' => './ruleset/site-futu.mrs',
            'interval' => 86400,
        ],
        'site-itiger' => [
            'type' => 'http',
            'behavior' => 'domain',
            'format' => 'mrs',
            'url' => 'https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/itiger.mrs',
            'path' => './ruleset/site-itiger.mrs',
            'interval' => 86400,
        ],
        'site-ibkr' => [
            'type' => 'http',
            'behavior' => 'domain',
            'format' => 'mrs',
            'url' => 'https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/ibkr.mrs',
            'path' => './ruleset/site-ibkr.mrs',
            'interval' => 86400,
        ],
        'site-cn' => [
            'type' => 'http',
            'behavior' => 'domain',
            'format' => 'mrs',
            'url' => 'https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/cn.mrs',
            'path' => './ruleset/site-cn.mrs',
            'interval' => 86400,
        ],
        'ip-cn' => [
            'type' => 'http',
            'behavior' => 'ipcidr',
            'format' => 'mrs',
            'url' => 'https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geoip/cn.mrs',
            'path' => './ruleset/ip-cn.mrs',
            'interval' => 86400,
        ],
    ],
    'rules' => [
        'DOMAIN-SUFFIX,local,DIRECT',
        'DOMAIN-SUFFIX,arpa,DIRECT',
        'RULE-SET,ip-private,DIRECT,no-resolve',
        'RULE-SET,ad-reject,REJECT',
        'DOMAIN,ai-gateway.vercel.sh,AI Services',
        'DOMAIN,api.github.com,AI Services',
        'DOMAIN,apple-relay.apple.com,AI Services',
        'DOMAIN,apple-relay.cloudflare.com,AI Services',
        'DOMAIN,apple-relay.fastly-edge.com,AI Services',
        'DOMAIN,cp4.cloudflare.com,AI Services',
        'DOMAIN,gateway.ai.cloudflare.com,AI Services',
        'DOMAIN,gateway.icloud.com,AI Services',
        'DOMAIN,gspe1-ssl.ls.apple.com,AI Services',
        'DOMAIN,guzzoni.apple.com,AI Services',
        'DOMAIN-KEYWORD,openai,AI Services',
        'DOMAIN-SUFFIX,ai.com,AI Services',
        'DOMAIN-SUFFIX,anthropic.com,AI Services',
        'DOMAIN-SUFFIX,cerebras.ai,AI Services',
        'DOMAIN-SUFFIX,chat.com,AI Services',
        'DOMAIN-SUFFIX,chatgpt.com,AI Services',
        'DOMAIN-SUFFIX,claude.ai,AI Services',
        'DOMAIN-SUFFIX,claude.com,AI Services',
        'DOMAIN-SUFFIX,clipdrop.co,AI Services',
        'DOMAIN-SUFFIX,dify.ai,AI Services',
        'DOMAIN-SUFFIX,grok.com,AI Services',
        'DOMAIN-SUFFIX,groq.com,AI Services',
        'DOMAIN-SUFFIX,jasper.ai,AI Services',
        'DOMAIN-SUFFIX,meta.ai,AI Services',
        'DOMAIN-SUFFIX,oaistatic.com,AI Services',
        'DOMAIN-SUFFIX,oaiusercontent.com,AI Services',
        'DOMAIN-SUFFIX,openart.ai,AI Services',
        'DOMAIN-SUFFIX,perplexity.ai,AI Services',
        'DOMAIN-SUFFIX,poe.com,AI Services',
        'DOMAIN-SUFFIX,smoot.apple.com,AI Services',
        'DOMAIN-SUFFIX,sora.com,AI Services',
        'DOMAIN-SUFFIX,x.ai,AI Services',
        'DOMAIN-SUFFIX,wifiman.com,Default Proxy',
        'RULE-SET,site-google,Default Proxy',
        'RULE-SET,site-apple,Microsoft & Apple',
        'RULE-SET,site-microsoft,Microsoft & Apple',
        'RULE-SET,site-steam-cn,Steam Download',
        'RULE-SET,site-category-game-platforms-download-cn,DIRECT',
        'DOMAIN-SUFFIX,steamcontent.com,Steam Download',
        'DOMAIN-SUFFIX,steamserver.net,Steam Download',
        'DOMAIN,steampipe.akamaized.net,Steam Download',
        'DOMAIN,steam.apac.qtlglb.com,Steam Download',
        'RULE-SET,site-category-game-platforms-download,Steam Download',
        'RULE-SET,site-category-entertainment,Stream',
        'RULE-SET,site-futu,Securities',
        'RULE-SET,site-itiger,Securities',
        'RULE-SET,site-ibkr,Securities',
        'RULE-SET,site-cn,DIRECT',
        'RULE-SET,ip-cn,DIRECT',
        'MATCH,Final Match',
    ],
    'tun' => [
        'stack' => 'mixed',
    ],
];
